# 
# Bases de Dados 2020/2021
# Trabalho Prático
#
# Trabalho realizado por:
#    Diogo Filipe    | uc2018288391@student.uc.pt
#    José Gomes      | uc2018286225@student.uc.pt
#    Pedro Marques   | uc2018285632@student.uc.pt
version: '3'

services:
  db:
    build: ./postgresql
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: ./python
    container_name: api
    volumes:
      - "./python/app:/app"
    expose:
      - "5000"
    ports:
      - "8080:5000"
    depends_on:
      - db